### ISSUE TITLE
Website is not up-to-date...

### ISSUE THREAD

**Issue by Neustradamus** [lunarmodules/luasocket#357]
On https://github.com/lunarmodules/luasocket, I see:
```
Network support for the Lua language
http://www.impa.br/~diego/software/luasocket
```

This website is not up-to-date and has dead links.

Time to update?

**Comment by alerque** [comment]
Yes, very much time. But we're just getting the shape of the repo together after the migration to this namespace. I think at this point the urgency is on getting out a release that includes the fixes needed for Lua 5.4.3+ into a tagged release, then sorting through the backlog and getting everything cleaned up. I'm sure we'll re-host the documentation based on this repo location, but getting that all together may happen after a release rather than before.

**Comment by alerque** [comment]
In the mean time if you want to contribute I'd be grateful for any PR review/comments on anything that touches the `doc/` dir and will gladly review and accept PRs to that content with obvious fixes. I wouldn't try to completely overhaul the documentation since we'll probably switch to `ldoc` for that, but fixing URLs and such would be very welcome.

**Comment by alerque** [comment]
Docs have been rebuild and links updated for some time now.
