### ISSUE TITLE
unable to compile in 64bits for windows

### ISSUE THREAD

**Issue by Ligneel** [lunarmodules/luasocket#376]
I would like some help on the procedure to follow to compile this for a 5.1 64 bit lua on windows.
I've been trying for a few days but programming isn't what I do for work and I've never compiled/worked with lua before and the whole thing is super confusing.
Any help would be greatly appreciated!

(I've managed to compile it for linux when running ubuntu on windows but for windows i'm stuck)

what i've tried that seems to make the most sense so far is :
- editing win64.cmd to change lua version to 5.1
- editing vc64.bat to give it the proper path for vcvars64.bat
- editing the makefiles in luasocket-master/ and luasocket-master/src to change the build platform to win64
- starting win64.cmd (not if it does anything)
- starting vc64.bat (opens the mingw64 thing)
- cd to the luasocket-master/ folder
- make

this is the error I get :
![image](https://user-images.githubusercontent.com/25638371/163663069-e418cb6e-41f3-43d5-a2e6-133af5d784a3.png)

Did I do anything wrong up to this point?
I've tried grabbing missing files from other places on my computer but they just reference other files util i get an error. And a lot of them have include <something> which seems to break things but i "fixed?" that by replacing <> by ""
The most promising solution so far has been installing lua 5.1 for windows with chocolatey and then grabbing the missing files from there and add them to  luasocket-master/src :
![image](https://user-images.githubusercontent.com/25638371/163663514-e599a59e-918b-4ac9-ae8d-6c2a3b90e896.png)
At this point it does things, albeit with a bunch of errors but then gets stuck here:
`LINK : fatal error LNK1104: cannot open file 'C:\Program Files\Git\LIBPATH;C:\Program Files\Git\lib\lua\5.1\x64\Release.obj'`
(I do not have this file anywhere on my computer)

Alternatively I've just tried to open it with visual studio again (community 2022) and it's just giving some errors instead of the many i had before that i had no idea how to fix:
![image](https://user-images.githubusercontent.com/25638371/163664985-d28cf17d-8782-4635-b6be-d8da0c725d29.png)
How can i tell it to look for lua51.dll instead?

**Comment by alerque** [comment]
I'm not on Windows and haven't been for 25 years, but it seems like the bit you may be missing is specifying the base path to your Lua source header files. In fact several of the steps you took should have been unnecessary. Editing files in the luasocket source should not be needed, you just need a few ENV variables setup correctly so that it knows where your system stuff is (especially the Lua 5.1 sources) relative to the build location.

I would actually start from scratch and try using LuaRocks first. Do you have a working `luarocks` in Windows? And can you `luarocks install luasocket`? The advantage of this is that it knows a lot about where other Lua related stuff will be on your system and can likely wire up all the necessary environment variables.

If that works you can move on to perhaps downloading the source yourself and using `luarocks build`. That should get you everything you need, but if you still need to use the manual `make` method at least you'd be able to reference what environment variables were being used, such as where your Lua headers are.

**Comment by Ligneel** [comment]
I can do that yes but I beleive it's building 32 bit files and they don't work in the program i'm using which i believe is using 64bit.

**Comment by Ligneel** [comment]
Actually nvm since I assume you don't use VS from your message :p.
So using luarocks build gives the following.
![image](https://user-images.githubusercontent.com/25638371/163665161-c8ff6930-2f2b-4f5d-af70-6a18f4a08376.png)
So I guess I need to install lua in 64 bit somehow. I thought i did that but I guess not.

**Comment by alerque** [comment]
Your are correct I don't use VS ;-)

And also correct, you will need a working Lua built with 64 bit support and matching header files somewhere before you can even approach building this library.

**Comment by Ligneel** [comment]
I forgot to say but thanks for the help. ;D
could you clarify the thing about the header parts? I don't mind doing my own research but so i have directions on how to approach it.

**Comment by alerque** [comment]
The header files you need are part of the Lua sources. You need a built version of Lua of course, but in order to build other things like libraries that match with and can be loaded as modules into it, they must be able to reference the sources that match your Lua install. For example on Linux a Lua 5.1 installation might come with the binary in `/usr/bin` and some shared libraries in `/usr/lib`, but it will also include a number of `*.h` files in `/usr/include/lua5.1/`. Any time I build something for Lua5.1 there is usually an argument or environment variable that specifies where this folder is.

This project has some standard ones filled in already. It looks like if you run

```
make PLAT=win64 LUAV=5.1
```

...the `src/makefile` will look here:

```makefile
LUAINC_win64?=$(LUAPREFIX_win64)/include/lua/$(LUAV) $(LUAPREFIX_win64)/include/lua$(LUAV)
```

It looks like you may need to set `LUAPREFIX_win64` yourself.

```
make PLAT=win64 LUAV=5.1 LUAPREFIX_win64="/c/base/path/to/include/dir"
```

**Comment by Ligneel** [comment]
It does look like I have a 64bit install of lua now as if i check the dll it makes with a tool called dependencywalker it indicated they are x64:
![image](https://user-images.githubusercontent.com/25638371/163665808-8d10e90e-c2fe-45e8-bfc6-d10fbed79f58.png)
That being said i found this 32or64 function to test if it lua is using 32 or 64 and it indicated 32 if i run it.
https://stackoverflow.com/questions/48093429/determine-whether-lua-compiler-runs-32-or-64-bit
I'm not sure how trustworthy that function is but in the game I want to ultimated use sockets in it does say 64. And in that lua version i downloaded for which the dlls are 64 it says 32. So I'm a bit confused regarding that...

**Comment by alerque** [comment]
My the way the `cmd32.cmd` and `cmd64.cmd` files look like something an earlier maintainer hard coded to match their system and where they had sources. They don't look like generic things for others to use and should probably be removed / moved into documentation. But the latter of those is basically the command I've shown above, so I suspect you don't need to do any source editing at all, just get those paths right and call that command.

**Comment by alerque** [comment]
I'm not going to be much use for the 32 vs. 64 bit issue in Windows, but I assume once you have a working 64 bit Lua install this library should follow suit pretty easily.

**Comment by Ligneel** [comment]
Ggotcha. In which folder should LIBPATH end?

**Comment by Ligneel** [comment]
alright so editing  the makefile I think I got it working. It produced dlls, they are 64bit.
However when doing require ('socket') in the program I'm trying to use this with I now get:
![image](https://user-images.githubusercontent.com/25638371/163669190-7736f16a-4088-4402-bd72-bfdb6327195e.png)
Does that mean i compiled it incorrectly or would that relate to something else?

**Comment by Ligneel** [comment]
I think I somehow got stuff to work. Thanks a lot!

**Comment by alerque** [comment]
Somebody else contributed some Windows releated fixes that went into v3.1.0. I don't think it covered your specific set of issues, but it might be useful to revisit this and figure out what exactly if anything can be changed for the better here.

**Comment by ChroniKom** [comment]
Hi guys,

i dont have Visual Studio and all the Dependencies to compile the project to get the DLL Binaries
as well as i cannot have LuaRocks to install it.
as i'm trying to create Lua script for OBS, and share it for others, and i guess the guys who will get it, will not be able to "install" lua dependencies

could you guys please share binaries, for Windows 64bit?

for copy and paste them into Lua scripts project directory
to add custom ClassPath for the "require"d library in Lua script

thanks

**Comment by Ketho** [comment]
@alerque I don't normally use 64-bit lua binaries and mingw but LuaSocket 3.1.0-1 appears to work fine for me. It compiled and I tried a quick listener/talker test.

- lua-5.4.2_Win64_bin
- luarocks-3.9.1-windows-64
- [winlibs](https://winlibs.com/)-x86_64-posix-seh-gcc-12.1.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r3
(renamed `gcc.exe` to `mingw32-gcc.exe`)

![image](https://user-images.githubusercontent.com/1073877/184898369-877c45bd-0a2b-47e6-804d-209c9712f966.png)

**Comment by Ketho** [comment]
I just realize I'm using WinLibs MinGW, and the original issue was more related to Visual Studio.

I actually don't really know much about tooling myself, just that I can do `luarocks install luasocket` with the available lua binaries and a mingw distribution.

Better documentation for windows noobs like me would be great though.

**Comment by alerque** [comment]
I'm don't even have access to Windows to fiddle with, so any documentation improvements will have to be contributed by end users. I'm open to facilitating PRs if anybody wants to improve the docs we have for the benefit of future Windows users.
