### ISSUE TITLE
Excuse me, is there a compiled win version?

### ISSUE THREAD

**Issue by HsiangNianian** [lunarmodules/luasocket#399]
As an example, I need luasocket urgently recently, but I am too busy to compile it, and my computer is not around. Before going to bed, I posted this issue, hoping that someone can send me the compiled luasocket version of window. I would be very grateful.

**Comment by alerque** [comment]
No. It is distributed on LuaRocks and you should be able to build / install it using that. The upstream maintainer(s) don't have access to Windows machines to build or test on. We'd be happy to accept contributions from the community for fixes or even CI testing for Windows, but even then it will probably be up to end users to compile for their own target platforms.

**Comment by HsiangNianian** [comment]
Thank you very much for your help. I already know these reasons, and I will try to write ci for Windows platform and submit it to pr.

Hsiang Nianian,
此致。
________________________________

**Comment by Tieske** [comment]
Just a heads-up @HsiangNianian ; you cannot mix and match binaries on Windows. You have to ensure in any installation that all binaries are linked with the same VC runtime lib. If not you'll experience seemingly random crashes.

See https://github.com/luarocks/luarocks/issues/786 and https://github.com/luarocks/luarocks/issues/788.

LuaRocks even bundles a PE-parser to check the runtime from the binaries.

**Comment by alerque** [comment]
> We'd be happy to accept contributions from the community for fixes or even CI testing for Windows, but even then it will probably be up to end users to compile for their own target platforms.

What Tieske pointed out is spot on and the background for why I suggested to need CI jobs to test Windows builds, not necessarily to distribute binaries. Because there are so many different compilers and host system arrangements that would need to be covered it isn't really practical. The `luarocks` tool does pretty well at getting things built on different platforms. Having some upstream testing however would help a lot to make sure things are ship-shape at any given time and expected to work especially since few current upstream developers are actively using this on Windows.
